name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift build
  test:
    needs: build
    runs-on: macOS-latest
    steps:
    - run: brew install drafter
    - run: for f in Tests/SwiftBeakerTests/Examples/*.md; do drafter -f json "$f" > "$f.json"; done
    - run: swift test
  podspec:
    needs: build
    runs-on: macOS-latest
    steps:
    - run: bundle update --bundler
    - run: bundle install
    - run: bundle exec pod lib lint
